// Generated by BUCKLESCRIPT VERSION 4.0.6, PLEASE EDIT WITH CARE
'use strict';

var $$Array = require("bs-platform/lib/js/array.js");
var Belt_Option = require("bs-platform/lib/js/belt_Option.js");
var Js_mapperRt = require("bs-platform/lib/js/js_mapperRt.js");
var ReasonReact = require("reason-react/lib/js/src/ReasonReact.js");
var Js_null_undefined = require("bs-platform/lib/js/js_null_undefined.js");
var ReactNativeModal = require("react-native-modal");

var jsMapperConstantArray = /* array */[
  /* tuple */[
    -976943247,
    "slideInUp"
  ],
  /* tuple */[
    -912149825,
    "slideOutRight"
  ],
  /* tuple */[
    -784990497,
    "slideOutDown"
  ],
  /* tuple */[
    -784990497,
    "slideOutDown"
  ],
  /* tuple */[
    -696775036,
    "slideOutLeft"
  ],
  /* tuple */[
    -76707080,
    "slideInDown"
  ],
  /* tuple */[
    11508381,
    "slideInLeft"
  ],
  /* tuple */[
    268745862,
    "slideInRight"
  ],
  /* tuple */[
    1069605784,
    "slideOutUp"
  ]
];

function animationToJs(param) {
  return Js_mapperRt.binarySearch(9, param, jsMapperConstantArray);
}

var jsMapperConstantArray$1 = /* array */[
  /* tuple */[
    -1032980382,
    "down"
  ],
  /* tuple */[
    -944764921,
    "left"
  ],
  /* tuple */[
    -379319332,
    "right"
  ],
  /* tuple */[
    26203,
    "up"
  ]
];

function swipeDirectionToJs(param) {
  return Js_mapperRt.binarySearch(4, param, jsMapperConstantArray$1);
}

var jsMapperConstantArray$2 = /* array */[
  /* tuple */[
    -685814367,
    "landscape-right"
  ],
  /* tuple */[
    -55740357,
    "landscape"
  ],
  /* tuple */[
    402056674,
    "landscape-left"
  ],
  /* tuple */[
    923863087,
    "portrait-upside-down"
  ],
  /* tuple */[
    951001435,
    "portrait"
  ]
];

function orientationToJs(param) {
  return Js_mapperRt.binarySearch(5, param, jsMapperConstantArray$2);
}

function make(animationIn, animationOut, animationInTiming, animationOutTiming, avoidKeyboard, backdropColor, backdropOpacity, backdropTransitionInTiming, backdropTransitionOutTiming, isVisible, onBackButtonPress, onBackdropPress, onModalHide, onModalShow, onSwipe, scrollOffset, scrollOffsetMax, scrollTo, swipeThreshold, swipeDirection, useNativeDriver, hideModalContentWhileAnimating, supportedOrientations, style, children) {
  return ReasonReact.wrapJsForReason(ReactNativeModal.default, {
              isVisible: isVisible,
              animationIn: Js_null_undefined.fromOption(Belt_Option.map(animationIn, animationToJs)),
              animationInTiming: Js_null_undefined.fromOption(animationInTiming),
              animationOut: Js_null_undefined.fromOption(Belt_Option.map(animationOut, animationToJs)),
              animationOutTiming: Js_null_undefined.fromOption(animationOutTiming),
              avoidKeyboard: Js_null_undefined.fromOption(avoidKeyboard),
              backdropColor: Js_null_undefined.fromOption(backdropColor),
              backdropOpacity: Js_null_undefined.fromOption(backdropOpacity),
              backdropTransitionInTiming: Js_null_undefined.fromOption(backdropTransitionInTiming),
              backdropTransitionOutTiming: Js_null_undefined.fromOption(backdropTransitionOutTiming),
              onBackButtonPress: Js_null_undefined.fromOption(onBackButtonPress),
              onBackdropPress: Js_null_undefined.fromOption(onBackdropPress),
              onModalHide: Js_null_undefined.fromOption(onModalHide),
              onModalShow: Js_null_undefined.fromOption(onModalShow),
              onSwipe: Js_null_undefined.fromOption(onSwipe),
              scrollOffset: Js_null_undefined.fromOption(scrollOffset),
              scrollOffsetMax: Js_null_undefined.fromOption(scrollOffsetMax),
              scrollTo: Js_null_undefined.fromOption(scrollTo),
              swipeThreshold: Js_null_undefined.fromOption(swipeThreshold),
              swipeDirection: Js_null_undefined.fromOption(Belt_Option.map(swipeDirection, swipeDirectionToJs)),
              useNativeDriver: Js_null_undefined.fromOption(useNativeDriver),
              supportedOrientations: Js_null_undefined.fromOption(Belt_Option.map(supportedOrientations, (function (param) {
                          return $$Array.map(orientationToJs, param);
                        }))),
              hideModalContentWhileAnimating: Js_null_undefined.fromOption(hideModalContentWhileAnimating),
              style: Js_null_undefined.fromOption(style)
            }, children);
}

exports.make = make;
/* ReasonReact Not a pure module */
